
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
//export const CATEGORIA_ACTUAL = 'CATEGORIA_ACTUAL';
export const ELIMINAR_CATEGORIA = 'ELIMINAR_CATEGORIA';
export const AGREGAR_HISTORIA = 'AGREGAR_HISTORIA';
//export const HISTORIAS_CATEGORIAS = 'HISTORIAS_CATEGORIAS';
export const OBTENER_HISTORIAS = 'OBTENER_HISTORIAS';
export const OBTENER_HISTORIAS_TODAS = 'OBTENER_HISTORIAS_TODAS';

export const FORMULARIO_CATEGORIAS = 'FORMULARIO_CATEGORIAS';
export const OBTENER_CATEGORIAS = 'OBTENER_CATEGORIAS';
export const AGREGAR_CATEGORIA = 'AGREGAR_CATEGORIA';
export const CATEGORIA_ERROR = 'CATEGORIA_ERROR';
export const OBTENER_CATEGORIAS_TODAS = 'OBTENER_CATEGORIAS_TODAS';
//export const NUMERO_HISTORIAS_CATEGORIA = 'NUMERO_HISTORIAS_CATEGORIA';


export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXISTOSO = 'REGISTRO_EXISTOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS';